# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=35)),
                ('district', models.CharField(default='', max_length=100)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(default='', max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=15)),
                ('region', models.CharField(default='', max_length=26)),
                ('surface_area', models.FloatField(default=0.0)),
                ('indep_year', models.SmallIntegerField(blank=True, null=True)),
                ('population', models.IntegerField(default=0)),
                ('life_expectancy', models.FloatField(blank=True, null=True)),
                ('gnp', models.FloatField(blank=True, null=True)),
                ('gnp_old', models.FloatField(blank=True, null=True)),
                ('local_name', models.CharField(default='', max_length=46)),
                ('government_form', models.CharField(default='', max_length=45)),
                ('head_of_state', models.CharField(blank=True, max_length=60, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('code2', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Countrylanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('is_offical', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=1)),
                ('percentage', models.FloatField(default=0.0)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='countrylanguage',
            unique_together=set([('country_code', 'language')]),
        ),
    ]
